2016-12-30T07:06:14.385Z - info: 127.0.0.1 - - [30/Dec/2016:07:06:14 +0000] "GET /v2/subcategory/Owl HTTP/1.1" 200 - "-" "PostmanRuntime/3.0.5"

2016-12-30T07:06:25.594Z - error: uncaughtException: Cannot read property 'subCategory' of undefined date=Fri Dec 30 2016 12:36:25 GMT+0530 (IST), pid=12839, uid=501, gid=20, cwd=/Users/anshulsharma/Desktop/chibleetestbackend, execPath=/usr/local/bin/node, version=v4.4.7, argv=[/usr/local/bin/node, /Users/anshulsharma/Desktop/chibleetestbackend/server.js], rss=136036352, heapTotal=104991840, heapUsed=85331088, loadavg=[1.39306640625, 1.52001953125, 1.63134765625], uptime=301810
TypeError: Cannot read property 'subCategory' of undefined
    at /Users/anshulsharma/Desktop/chibleetestbackend/modules/login/server/controllers/login.server.controller.js:247:25
    at handleCallback (/Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongodb/lib/utils.js:96:12)
    at /Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongodb/lib/cursor.js:844:16
    at handleCallback (/Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:156:5)
    at setCursorNotified (/Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:506:3)
    at /Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:572:16
    at Object.queryCallback [as cb] (/Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:238:5)
    at /Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:443:18
    at authenticateStragglers (/Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:399:16)
    at null.messageHandler (/Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:421:5)
    at Socket.<anonymous> (/Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:294:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
2016-12-30T07:08:25.347Z - info: 127.0.0.1 - - [30/Dec/2016:07:08:25 +0000] "GET /v2/subcategory/undifined HTTP/1.1" - - "-" "PostmanRuntime/3.0.5"

2017-01-02T06:38:38.754Z - info: 127.0.0.1 - - [02/Jan/2017:06:38:38 +0000] "POST /v2/confirm-vendor HTTP/1.1" 200 33 "-" "PostmanRuntime/3.0.5"

2017-01-02T06:40:37.735Z - info: 127.0.0.1 - - [02/Jan/2017:06:40:37 +0000] "POST /v2/confirm-vendor HTTP/1.1" 200 33 "-" "PostmanRuntime/3.0.5"

2017-01-02T06:42:45.621Z - info: 127.0.0.1 - - [02/Jan/2017:06:42:45 +0000] "POST /v2/confirm-vendor HTTP/1.1" 200 33 "-" "PostmanRuntime/3.0.5"

2017-01-02T06:43:58.948Z - info: 127.0.0.1 - - [02/Jan/2017:06:43:58 +0000] "POST /v2/confirm-vendor HTTP/1.1" 200 33 "-" "PostmanRuntime/3.0.5"

2017-01-02T07:19:57.620Z - error: uncaughtException: connection timeout date=Mon Jan 02 2017 12:49:57 GMT+0530 (IST), pid=17108, uid=501, gid=20, cwd=/Users/anshulsharma/Desktop/chibleetestbackend, execPath=/usr/local/bin/node, version=v4.4.7, argv=[/usr/local/bin/node, /Users/anshulsharma/Desktop/chibleetestbackend/server.js], rss=39772160, heapTotal=76126304, heapUsed=73660344, loadavg=[2.0849609375, 2.38818359375, 2.40185546875], uptime=561836
Error: connection timeout
    at null.<anonymous> (/Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:168:17)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at listener (/Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongoose/node_modules/mongodb/lib/db.js:1791:14)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongoose/node_modules/mongodb/lib/server.js:270:14)
    at g (events.js:260:16)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongodb-core/lib/topologies/server.js:322:12)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongodb-core/lib/connection/pool.js:271:12)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (/Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongodb-core/lib/connection/connection.js:175:10)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at Socket._onTimeout (net.js:332:8)
    at _runOnTimeout (timers.js:524:11)
    at _makeTimerTimeout (timers.js:515:3)
    at Timer.unrefTimeout (timers.js:584:5)
2017-01-02T07:45:39.415Z - info: 127.0.0.1 - - [02/Jan/2017:07:45:39 +0000] "POST /api/vendortouserchat HTTP/1.1" 404 34 "-" "PostmanRuntime/3.0.5"

2017-01-02T07:46:03.923Z - error: uncaughtException: Cannot read property '_id' of null date=Mon Jan 02 2017 13:16:03 GMT+0530 (IST), pid=17668, uid=501, gid=20, cwd=/Users/anshulsharma/Desktop/chibleetestbackend, execPath=/usr/local/bin/node, version=v4.4.7, argv=[/usr/local/bin/node, /Users/anshulsharma/Desktop/chibleetestbackend/server.js], rss=138158080, heapTotal=104991840, heapUsed=85993584, loadavg=[1.513671875, 1.77880859375, 1.95947265625], uptime=563402
TypeError: Cannot read property '_id' of null
    at /Users/anshulsharma/Desktop/chibleetestbackend/modules/vendorapp/server/controllers/vendorapp.server.controller.js:622:28
    at Query.<anonymous> (/Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongoose/lib/model.js:3369:16)
    at /Users/anshulsharma/Desktop/chibleetestbackend/node_modules/kareem/index.js:259:21
    at /Users/anshulsharma/Desktop/chibleetestbackend/node_modules/kareem/index.js:127:16
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)
